# Generated by Django 3.0.3 on 2020-03-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='video_src',
        ),
    ]
